### ISSUE TITLE
Andrii's work integration

### ISSUE THREAD

**Issue by adouge** [adouge/solensim#41]
Add structure to how you interact with the repo, since we intend to finish this shit together.

Поставь teamviewer, на след неделе подключим тебе гит нормально. Пока еще нет интерфейса к твоему коду, так что просто организованно тут лежать будет; полезно использовать орг возможности платформы. Потом, как прогресс по направлению бечелорарбайта будет, будем рассматривать интеграцию.

Todo для меня:
 - /mcode/ dir
 - git setup (teamviewer)
 - github workflow crashcourse

**Comment by andrii302** [comment]
Let's Tuesday after call
